apiVersion: v1
kind: Namespace
metadata:
  name: flash-sale-infra
  labels:
    app.kubernetes.io/part-of: flash-sale
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: flash-sale-dev
  labels:
    app.kubernetes.io/part-of: flash-sale
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: flash-sale-observability
  labels:
    app.kubernetes.io/part-of: flash-sale
    environment: dev

